spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: Tlias
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
    map-underscore-to-camel-case: true

qiniuyun:
  oss:
    accessKey: bjxv3VdZBTqbl-XFEc9_om74i1YlPSne9B_tRjBR
    secretKey: fKYRONIda8SGaOLmKthzg1_cLeNYyWu04lt7diZu
    bucket: swimmingliu
jwt:
  signkey: swimmingliuwq3kj5rhjkqehrfjksdbtgregjlwernwetnerhgweteqryuq4
  expire: 43200000